// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Diagnostics;
using System.Net.Http;
using System.Threading.Tasks;
using Foundation;
using Sitecore.MobileSDK.API.Items;
using UIKit;
using UTStoreDemo.Helpers;

namespace UTStoreDemo.UI
{
	public partial class CountryNavigationCell : UITableViewCell
	{
        
        public CountryNavigationCell (IntPtr handle) : base (handle)
		{

        }

        public async void SetItem(ISitecoreItem item, HttpClient httpClient)
        {
            this.CountryName.Text = item[SCHelper.TitleFieldName].RawValue;
            this.CountryDescription.Text = item[SCHelper.EntryFieldName].RawValue.Replace(System.Environment.NewLine, " ");
            string code = item[SCHelper.CountryCodeFieldName].RawValue.ToLower();

            try
            {
                byte[] imageContent = await ImageHelper.LoadCountryFlagContent(code, httpClient);
                this.CountryImage.Image = UIImage.LoadFromData(NSData.FromArray(imageContent));
            }
            catch(Exception e)
            {
                Debug.WriteLine("ERROR: Country flag image is not available: " + e.ToString());

                //do nothing
            }

            this.CountryImage.Layer.BorderColor = UIColor.Black.CGColor;
            this.CountryImage.Layer.BorderWidth = 1;
        }

       
    }
}
