// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using Sitecore.MobileSDK.API.Items;
using Sitecore.MobileSDK.API.Session;
using SSCExtensions;
using UIKit;
using UTStoreDemo.Helpers;
using UTStoreDemo.UI;

namespace UTStoreDemo
{
	public partial class RegionsViewController : UITableViewController
	{
        DataSource dataSource;


        protected RegionsViewController(IntPtr handle) : base(handle)
        {
            // Note: this .ctor should not contain any initialization logic.
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            Title = NSBundle.MainBundle.GetLocalizedString("Regions");
        }

        public override void ViewWillAppear(bool animated)
        {
            ClearsSelectionOnViewWillAppear = SplitViewController.Collapsed;
            base.ViewWillAppear(animated);

            this.UploadRegions();
        }

        private async void UploadRegions()
        {
            if (dataSource == null)
            {
                ScItemsResponse response = await NetworkHelper.GetAllRegions();
                TableView.Source = dataSource = new DataSource(this, response);
            }
            TableView.ReloadData();
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
            // Release any cached data, images, etc that aren't in use.
        }



        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            if (segue.Identifier == "showCountries")
            {
                CountriesViewController controller = (CountriesViewController)segue.DestinationViewController;
                var indexPath = TableView.IndexPathForSelectedRow;
                var item = dataSource.Objects[indexPath.Row];

                controller.CurrentRegion = item;
                controller.NavigationItem.LeftBarButtonItem = SplitViewController.DisplayModeButtonItem;
                controller.NavigationItem.LeftItemsSupplementBackButton = true;
            }
        }

        class DataSource : UITableViewSource
        {
            static readonly NSString CellIdentifier = new NSString("Cell");
            readonly ScItemsResponse objects;
            readonly RegionsViewController controller;

            public DataSource(RegionsViewController controller, ScItemsResponse data)
            {
                this.controller = controller;
                this.objects = data;
            }

            public ScItemsResponse Objects
            {
                get { return objects; }
            }

            // Customize the number of sections in the table view.
            public override nint NumberOfSections(UITableView tableView)
            {
                return 1;
            }

            public override nint RowsInSection(UITableView tableview, nint section)
            {
                return objects.ResultCount;
            }

            // Customize the appearance of table view cells.
            public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
            {
                RegionNavigationCell cell = (RegionNavigationCell)tableView.DequeueReusableCell(CellIdentifier, indexPath);

                cell.SetItem(objects[indexPath.Row]);

                return cell;
            }

            public override bool CanEditRow(UITableView tableView, NSIndexPath indexPath)
            {
                // Return false if you do not want the specified item to be editable.
                return false;
            }


        }
    }
}
