// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Sitecore.MobileSDK.API.Items;
using UIKit;
using UTStoreDemo.Helpers;

namespace UTStoreDemo
{
	public partial class CitiesViewController : UITableViewController
	{
        DataSource dataSource;
        public ISitecoreItem CurrentCountry = null;

        protected CitiesViewController(IntPtr handle) : base(handle)
        {
            // Note: this .ctor should not contain any initialization logic.
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            Title = NSBundle.MainBundle.GetLocalizedString("Cities");
        }

        public override void ViewWillAppear(bool animated)
        {
            ClearsSelectionOnViewWillAppear = SplitViewController.Collapsed;
            base.ViewWillAppear(animated);

            this.GetCitiesForCountry(this.CurrentCountry);
        }

        public async void GetCitiesForCountry(ISitecoreItem country)
        {
            if (dataSource == null)
            {
                ScItemsResponse response = await NetworkHelper.GetCitiesForCountry(country);
                TableView.Source = dataSource = new DataSource(this, response);
            }

            TableView.ReloadData();
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
            // Release any cached data, images, etc that aren't in use.
        }



        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            if (segue.Identifier == "showCityDetails")
            {
                var controller = (DetailViewController)((UINavigationController)segue.DestinationViewController).TopViewController;
                var indexPath = TableView.IndexPathForSelectedRow;
                var item = dataSource.Objects[indexPath.Row];

                controller.SetDetailItem(item);
                controller.NavigationItem.LeftBarButtonItem = SplitViewController.DisplayModeButtonItem;
                controller.NavigationItem.LeftItemsSupplementBackButton = true;
            }
        }

        class DataSource : UITableViewSource
        {
            static readonly NSString CellIdentifier = new NSString("Cell");
            readonly ScItemsResponse objects;
            readonly CitiesViewController controller;

            public DataSource(CitiesViewController controller, ScItemsResponse data)
            {
                this.controller = controller;
                this.objects = data;
            }

            public ScItemsResponse Objects
            {
                get { return objects; }
            }

            // Customize the number of sections in the table view.
            public override nint NumberOfSections(UITableView tableView)
            {
                return 1;
            }

            public override nint RowsInSection(UITableView tableview, nint section)
            {
                return objects.ResultCount;
            }

            // Customize the appearance of table view cells.
            public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
            {
                var cell = tableView.DequeueReusableCell(CellIdentifier, indexPath);

                cell.TextLabel.Text = objects[indexPath.Row]["Title"].RawValue;

                return cell;
            }

            public override bool CanEditRow(UITableView tableView, NSIndexPath indexPath)
            {
                // Return false if you do not want the specified item to be editable.
                return false;
            }


        }
    }
}
