// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Sitecore.MobileSDK.API.Items;
using UIKit;
using UTStoreDemo.Helpers;

namespace UTStoreDemo.UI
{
	public partial class RegionNavigationCell : UITableViewCell
	{
		public RegionNavigationCell (IntPtr handle) : base (handle)
		{
		}

        public void SetItem(ISitecoreItem item)
        {
            string Title = item[SCHelper.TitleFieldName].RawValue;
            this.RegionName.Text = Title;
            this.RegionIcon.Image = UIImage.FromFile("Images/"+ Title + ".png");

        }
    }
}
